### ISSUE TITLE
ImportError: No module named ppl

### ISSUE THREAD

**Issue by MrRubyRed** [haudren/pyparma#3]
Hi,

I usually don't have the habit of installing packages, and I am running into some trouble trying to install pyparma. I downloaded ppl-1.2 and installed it using "./configure; make; sudo make install". I then downloaded pyparma-0.5.0 and ran "python setup.py build && python setup.py install". Finally, I type python and in the python console I write "import pyparma". I get the following error message:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyparma/__init__.py", line 3, in <module>
    from .ppl import *
ImportError: No module named ppl`

I suspect this has something to do with what says in the README: "To build it you need to have both the *ppl* and *gmp* libraries installed in a place where distutils can find it". 
- How can I know whether it is (a) a problem of ppl (b) a problem of gmp (c) or a problem of distutils?

I don't have much experience installing packages so sorry in advance if my question is very basic.

Thanks.

**Comment by haudren** [comment]
Hi

Given that the error happens at import time, I think that indeed we have a distutils problem. Can you try to uninstall pyparma and reinstall it using one of those ways:
- Use `pip install .` instead of `python setup.py install`
- Use `pip install pyparma` to directly install it from PyPI.

Note that in general it is not useful to install `ppl` from source: I simply `apt-get install libppl-dev`.

**Comment by MrRubyRed** [comment]
Thanks for the quick response,

I did try both of your approaches (uninstalling and pip-ing) but neither worked for me. 

In terms of ppl installation,  I am using a Mac OS X, and I did try both installing ppl from source and also using `brew install ppl`. How do I ensure python can access my ppl installation?

**Comment by haudren** [comment]
Hum interesting, I never tried to use this software on MacOS, so that would explain the error. Can you check that `python setup.py build_ext` does generate a `ppl.dylib` or `ppl.so` file in your build directory?

If it does, can you try to `cd` to that directory, open a python shell and `import ppl`?

**Comment by haudren** [comment]
Oh and also, can you check that in the install directory you have a shared library installed ?

**Comment by seedship** [comment]
EDIT: nevermind I just installed it from pip and it worked

I have the same issue, and I am on Arch Linux.

The output from my build is as follows

```
[seedship@triple-destinies pyparma]$ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/pyparma
copying pyparma/__init__.py -> build/lib.linux-x86_64-3.9/pyparma
creating build/lib.linux-x86_64-3.9/pyparma/utils
copying pyparma/utils/representations.py -> build/lib.linux-x86_64-3.9/pyparma/utils
copying pyparma/utils/__init__.py -> build/lib.linux-x86_64-3.9/pyparma/utils
copying pyparma/types.pxd -> build/lib.linux-x86_64-3.9/pyparma
copying pyparma/pylong.pxd -> build/lib.linux-x86_64-3.9/pyparma
copying pyparma/mpz.pxd -> build/lib.linux-x86_64-3.9/pyparma
copying pyparma/ppl_shim.hh -> build/lib.linux-x86_64-3.9/pyparma
copying pyparma/ppl_shim.cc -> build/lib.linux-x86_64-3.9/pyparma
running build_ext
cythoning pyparma/pylong.pyx to pyparma/pylong.c
/usr/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pyparma/pyparma/pylong.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: pyparma/types.pxd:19:4: 'mp_limb_t' redeclared 
warning: pyparma/pylong.pyx:33:4: 'Py_hash_t' redeclared 
cythoning pyparma/ppl.pyx to pyparma/ppl.cpp
/usr/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pyparma/pyparma/ppl.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: pyparma/types.pxd:19:4: 'mp_limb_t' redeclared 
warning: pyparma/ppl.pyx:1038:90: local variable 'maximum' referenced before assignment
warning: pyparma/ppl.pyx:1050:109: local variable 'maximum' referenced before assignment
warning: pyparma/ppl.pyx:1119:90: local variable 'minimum' referenced before assignment
warning: pyparma/ppl.pyx:1131:109: local variable 'minimum' referenced before assignment
building 'pyparma.pylong' extension
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/pyparma
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.9 -c pyparma/pylong.c -o build/temp.linux-x86_64-3.9/pyparma/pylong.o
pyparma/pylong.c: In function ‘__pyx_f_7pyparma_6pylong_mpz_get_pylong_large’:
pyparma/pylong.c:1196:13: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from incompatible pointer type ‘PyLongObject *’ {aka ‘struct _longobject *’} [-Wincompatible-pointer-types]
 1196 |   __pyx_t_2 = _PyLong_New(__pyx_v_pylong_size); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 59, __pyx_L1_error)
      |             ^
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.9/pyparma/pylong.o -L/usr/lib -lgmp -lgmpxx -o build/lib.linux-x86_64-3.9/pyparma/pylong.cpython-39-x86_64-linux-gnu.so
building 'pyparma.ppl' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.9 -c pyparma/ppl.cpp -o build/temp.linux-x86_64-3.9/pyparma/ppl.o -fPIC
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.9 -c pyparma/ppl_shim.cc -o build/temp.linux-x86_64-3.9/pyparma/ppl_shim.o -fPIC
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.9/pyparma/ppl.o build/temp.linux-x86_64-3.9/pyparma/ppl_shim.o -L/usr/lib -lppl -lgmpxx -o build/lib.linux-x86_64-3.9/pyparma/ppl.cpython-39-x86_64-linux-gnu.so
```

Furthermore, this is the contents of my build directory, there is no ppl.dylib or ppl.so
```
[seedship@triple-destinies build]$ ls
lib.linux-x86_64-3.9  temp.linux-x86_64-3.9
```

What should I do?
